### ISSUE TITLE
"adding edges to this graph type is not performant"

### ISSUE THREAD

**Issue by chriscoey** [sbromberger/SimpleWeightedGraphs.jl#5]
https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl/blob/16656e4c981e3c7147fe3320d4cd8ae2c71e3bfb/src/simpleweighteddigraph.jl#L85

This made me sad. Is there a plan to make it performant?

**Comment by sbromberger** [comment]
@chriscoey nope, unfortunately there's no way to make edge addition performant with SimpleWeightedGraphs. The reason is that the graph backend is a sparse matrix, and inserting into a sparse matrix can be expensive (relative to constant time). The SimpleWeightedGraph is best suited for graphs that you only have to create once (and don't modify extensively). If that doesn't meet your needs, you might try [MetaGraphs](https://github.com/JuliaGraphs/MetaGraphs.jl) which, in addition to being more flexible in terms of the metadata they can store, give you decent modification performance as well.

**Comment by chriscoey** [comment]
Understood. Thank you.

**Comment by timholy** [comment]
This warning is gratuitous if performance is not a paramount concern. Is there a way to suppress it? Or can it at least suggest a concrete substitute? If the substitute isn't simple, could it print a URL to a doc section that describes how to replace "old" code based on this package with something that is performant?

**Comment by sbromberger** [comment]
The substitute is to use a graph structure that has good insertion performance, but there’s really nothing better that tracks weights. I agree that we should probably move the message from the warning to the documentation. PRs welcome :)

**Comment by timholy** [comment]
That's an opening big enough to drive a truck through. Revving up engines now...

**Comment by simonschoelly** [comment]
I think what we could use is a graph type, where the edge properties are also in an adjacency list. Then adding edges and looking up edge properties both have logarithmic cost.

**Comment by sbromberger** [comment]
Now that we have named tuples this might be an interesting exercise.
